language: node_js
node_js:
- '8'
deploy:
  - provider: s3
    access_key_id: "$ACCESSKEYID"
    secret_access_key: "$SECRETACCESSKEY"
    local_dir: dpl_cd_upload
    region: us-west-1
    skip_cleanup: true
    on: &1
      repo: TowerofGiraffes/beachRNR-booking-service
    bucket: booking-service-s3
  - provider: codedeploy
    access_key_id: "$ACCESSKEYID"
    secret_access_key: "$SECRETACCESSKEY"
    bucket: booking-service-s3
    key: latest.zip
    bundle_type: zip
    application: Booking-Service
    deployment_group: Booking-Service-Group
    region: us-west-1
    on: *1
before_deploy:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
