language: node_js
node_js:
- '8'
deploy:
  - provider: s3
    access_key_id: "$ACCESSKEYID"
    secret_access_key:
      secure: PlQQrESlhB2vc1rrAlBH0r1mkxJvUX0ZuEIHjJ8Waa2CHxsbL2LofuyH0TUzP+CWqTOOmkW53NwjXD7bh9SuG3o12UYSjiO9uFcaxyj7kFhAUrrsqy3OFe6LRflONKoYqzx+giUZyrDeQabsvG1PE1IMKYCIAN3RgPifzmTMrjagYHIbFJ83AlKU8ChQXWDSCxSjpZ5XGG9rcmFWDcOYAesWWLH6gh2jljdTqlbpeVZ8OFOry2jGVwhpqnFUG7ZVmiZXAHgOx1WcqPWNqII4kCgKFoD6tpryUMWdTVdGL8y/g9uWG6U3Qr9ko3uG9RxY2W902TDpLqWgh5s77PoOp2o/LrLh+HAKO+4Y1ljhLY9YWmAhSL6ueo4LWaSomi0HlUZnYN6VnDvbGI+dd70HIILmdW8w6jhrOV92UdQRG7R7n4JKENJ/JEK+82Ovt2EhH51pTEC6mS1g1gUCBE37gwvBy5MEIi02uf9xFIoEG8R6qQSaHAkj3gnO66YKlZ6nGImg+hdO0LSGaKeXojJMS1l7vRiZKJkPBIapJJuRuW5oaMbLcCsAXRZ61BYn/FNRuDZwnRzT55xdi5jT+OeX1JyNupOQpOuKC1eCBOpE8qT0Rwx8DlVFQGmKutpiIi3txt9id31wo3R3dIO5eL2nEE2YTCkPBorzq1UC9khrUmg=
    local_dir: dpl_cd_upload
    region: us-west-1
    skip_cleanup: true
    on: &1
      repo: TowerofGiraffes/beachRNR-booking-service
    bucket: booking-service-s3
  - provider: codedeploy
    access_key_id: "$ACCESSKEYID"
    secret_access_key:
      secure: PlQQrESlhB2vc1rrAlBH0r1mkxJvUX0ZuEIHjJ8Waa2CHxsbL2LofuyH0TUzP+CWqTOOmkW53NwjXD7bh9SuG3o12UYSjiO9uFcaxyj7kFhAUrrsqy3OFe6LRflONKoYqzx+giUZyrDeQabsvG1PE1IMKYCIAN3RgPifzmTMrjagYHIbFJ83AlKU8ChQXWDSCxSjpZ5XGG9rcmFWDcOYAesWWLH6gh2jljdTqlbpeVZ8OFOry2jGVwhpqnFUG7ZVmiZXAHgOx1WcqPWNqII4kCgKFoD6tpryUMWdTVdGL8y/g9uWG6U3Qr9ko3uG9RxY2W902TDpLqWgh5s77PoOp2o/LrLh+HAKO+4Y1ljhLY9YWmAhSL6ueo4LWaSomi0HlUZnYN6VnDvbGI+dd70HIILmdW8w6jhrOV92UdQRG7R7n4JKENJ/JEK+82Ovt2EhH51pTEC6mS1g1gUCBE37gwvBy5MEIi02uf9xFIoEG8R6qQSaHAkj3gnO66YKlZ6nGImg+hdO0LSGaKeXojJMS1l7vRiZKJkPBIapJJuRuW5oaMbLcCsAXRZ61BYn/FNRuDZwnRzT55xdi5jT+OeX1JyNupOQpOuKC1eCBOpE8qT0Rwx8DlVFQGmKutpiIi3txt9id31wo3R3dIO5eL2nEE2YTCkPBorzq1UC9khrUmg=
    bucket: booking-service-s3
    key: latest.zip
    bundle_type: zip
    application: Booking-Service
    deployment_group: Booking-Service-Group
    region: us-west-1
    on: *1
before_deploy:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
